// Mocks generated by Mockito 5.1.0 from annotations
// in sua_musica_teste/test/features/details/usecase/get_generer_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sua_musica_teste/features/details/domain/services/details_services.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [DetailsServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockDetailsServices extends _i1.Mock implements _i2.DetailsServices {
  MockDetailsServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<Map<String, dynamic>>> getGenereByGame({List<int>? listId}) =>
      (super.noSuchMethod(
              Invocation.method(#getGenereByGame, [], {#listId: listId}),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i3.Future<List<Map<String, dynamic>>>);
  @override
  _i3.Future<List<Map<String, dynamic>>> getPlataforms({List<int>? listId}) =>
      (super.noSuchMethod(
              Invocation.method(#getPlataforms, [], {#listId: listId}),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i3.Future<List<Map<String, dynamic>>>);
}
